name: CI

on:
  pull_request:
    branches: 
      - master
  push:
    branches:
      - master

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Install miniconda
      uses: s-weigand/setup-conda@v1
      with:
        - update-conda: true
    - name: Install dependencies
      run: |
        conda install --file requirements.txt
        conda install -c rdkit rdkit
        # NOTE(kearnes): Remove version when 2.5.0 is fixed.
        conda install pylint=2.4.4
    - name: Install ord_schema
      run: |
        cd "${GITHUB_WORKSPACE}"
        echo "$(which python)"
        python setup.py install
    - name: Run tests
      run: |
        shopt -s globstar
        cd "${GITHUB_WORKSPACE}"
        for TEST_FILENAME in ord_schema/**/*_test.py; do \
          echo "Running tests in ${TEST_FILENAME}"; \
          python "${TEST_FILENAME}"; \
        done
    - name: Run pylint
      run: |
        cd "${GITHUB_WORKSPACE}"
        pylint ord_schema
    - name: Test notebooks
      run: |
        pip install treon
        treon
